### ISSUE TITLE
Symfony vendor there is an issue with generating client token

### ISSUE THREAD

**Issue by ovaisrafiqcs** [cometcult/CometCultBraintreeBundle#10]
I have resolved that by adding factory method in class in vendor/braintree/braintree_php/lib/Braintree/ClientToken.php
	public static function factory($attributes)
    {
        $instance = new self();
        return $instance;
    }

In controller
$tokenService = $factory->get('clienttoken');
$token = $tokenService::generate();

above code works and generate the token but without modifying the parent class its not possible please help on that.

I want that class to get updated on git so I can download the clienttoken working correctly in updated copy.

Please reply on that.

Thanks

**Comment by grEvenX** [comment]
Closing this one, see #12.

**Comment by grEvenX** [comment]
Can you confirm if the solution in #12 works ok for you?

**Comment by ovaisrafiqcs** [comment]
Hi,

No it didn’t worked on that time so I rather then used that service I used braintree library and include those things like below:

 

use Braintree_Configuration;

use Braintree_ClientToken;

use Braintree_Transaction;

 

  Braintree_Configuration::environment($environment);

                  Braintree_Configuration::merchantId($merchant_id);

                  Braintree_Configuration::publicKey($public_key);

                  Braintree_Configuration::privateKey($private_key);

                  $clientToken = Braintree_ClientToken::generate();

 

Thanks

 

Regards,

Ovais
