### ISSUE TITLE
How do you go about generating a ClientToken?

### ISSUE THREAD

**Issue by scyrma** [cometcult/CometCultBraintreeBundle#12]
Hi,

This is not a bug per-se, but looking how the code only returns classes with factory methods, I'm curious to know what is the designed way of using this bundle to call Braintree_ClientToken::generate()?

Thanks

**Comment by flomerz** [comment]
+1
I also want to know how to do this.

For now I use:
``
\Braintree_ClientToken::generate()
``

**Comment by mamartins** [comment]
+1

**Comment by grEvenX** [comment]
Can any of you confirm if the solution in #12 is ok for you?

**Comment by mamartins** [comment]
yes, I can call the method, and I have to do so in many functions that do not have factory, and sometimes even with some that do have factory but require parameters

**Comment by grEvenX** [comment]
@mamartins I mean with change I added in 4621db0, are you able use the code without having to get the factory before calling the static methods.

You should now be able to just call the following code as long as the CometCultBraintreeBundle is loaded:
```php
\Braintree_ClientToken::generate()
```

**Comment by mamartins** [comment]
ah, sorry. yes! :)

**Comment by marianflorin** [comment]
@grEvenX - This solution doesn't work, at least for me. From what I tested the calls in https://github.com/cometcult/CometCultBraintreeBundle/blob/4621db02708e2ad1c65733d3dd3cb6e538d7e510/DependencyInjection/CometCultBraintreeExtension.php are executed only when the Symfony cache is generated. These calls are setting a PHP static variable, so they should be executed on every page load. What worked for me was to override the `boot` method in `app/AppKernel.php` file, like below:
```
public function boot()
{
    parent::boot();
          \Braintree_Configuration::environment($this->getContainer()->getParameter('braintree.environment'));
\Braintree_Configuration::merchantId($this->getContainer()->getParameter('braintree.merchant_id'));
\Braintree_Configuration::publicKey($this->getContainer()->getParameter('braintree.public_key'));
\Braintree_Configuration::privateKey($this->getContainer()->getParameter('braintree.private_key'));
}
```
