### ISSUE TITLE
ClientToken

### ISSUE THREAD

**Issue by btribouillet** [cometcult/CometCultBraintreeBundle#14]
Hi,

Great work !

Just  a question. How would you generate the ClientToken. I didn't see with the actual factory how to do.

I added in the factory :

    use Braintree_ClientToken;

    class BraintreeFactory
    {

        // ...

        public function getClientToken(){
            return Braintree_ClientToken::generate();
        }

    }

this is working (If it is the right way to do):

        $braintree = $this->get('braintree.factory');
        $transaction = $braintree->get('transaction');
        $transaction::sale(array('paymentMethodNonce' => $nonce));

but this is returning "Invalid service ClientToken" :

        $braintree = $this->get('braintree.factory');
        $braintree_token = $braintree->get('ClientToken');
        $braintree_token::generate();

**Comment by Itaelle** [comment]
Hey! Maybe you'll find a solution there: #12 ?

**Comment by btribouillet** [comment]
Thank you! Sorry for the late reply, i switched to another project.
Going back now on the braintree system. This should help ;).
